# Generated by Django 4.2.3 on 2023-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.TextField(max_length=50)),
                ('First_Name', models.TextField(max_length=20)),
                ('Last_name', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=40)),
                ('Phone_Number', models.TextField(max_length=12)),
                ('Address', models.TextField(max_length=35)),
                ('City', models.TextField(max_length=10)),
                ('Postal_Code', models.TextField(max_length=20)),
                ('User_Name', models.TextField(max_length=30)),
            ],
        ),
    ]
