# Generated by Django 4.2.3 on 2023-07-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_ID',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
