# Generated by Django 4.2.3 on 2023-07-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0003_remove_customer_id_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Phone_Number',
        ),
    ]
