# Generated by Django 4.2.3 on 2023-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0005_customer_phonee_number_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.TextField(max_length=20)),
                ('Last_name', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=40)),
                ('desciption', models.TextField(max_length=12)),
                ('price', models.TextField(max_length=35)),
                ('image', models.TextField(max_length=10)),
                ('Postal_Code', models.TextField(max_length=20)),
                ('category_id', models.TextField(max_length=30)),
            ],
        ),
    ]
