# Generated by Django 4.2.3 on 2023-07-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0006_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Postal_Code',
        ),
        migrations.RemoveField(
            model_name='products',
            name='email',
        ),
    ]
