# Generated by Django 4.2.3 on 2023-07-17 10:29

import app_Shop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0007_remove_products_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('categories_ID', models.AutoField(primary_key=True, serialize=False)),
                ('categories_name', models.TextField(max_length=20)),
                ('categories_image', models.TextField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_ID', models.TextField(max_length=30, verbose_name=app_Shop.models.categories)),
                ('quantity', models.TextField(max_length=20)),
                ('item_price', models.TextField(max_length=12)),
                ('Customer_ID', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app_Shop.customer')),
                ('Product_ID', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app_Shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_date', models.TextField(max_length=12)),
                ('Customer_ID', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app_Shop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='categories_ID',
            field=models.ForeignKey(default=1, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app_Shop.categories'),
            preserve_default=False,
        ),
    ]
