# Generated by Django 4.2.3 on 2023-07-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0008_categories_remove_products_category_id_order_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer_ID',
            new_name='Customer_ID_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categories_ID',
            new_name='categories_ID_id',
        ),
    ]
