# Generated by Django 4.2.3 on 2023-07-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0009_rename_customer_id_order_customer_id_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer_ID_id',
            new_name='Customer_ID',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='categories_ID_id',
            new_name='categories_ID',
        ),
    ]
