# Generated by Django 4.2.3 on 2023-07-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Shop', '0010_rename_customer_id_id_order_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='Order_ID',
            field=models.ForeignKey(default=1, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='app_Shop.order'),
            preserve_default=False,
        ),
    ]
